import type { Metadata } from "next";
import { Fredoka } from "next/font/google";
import "./globals.css";
import NavBar from "@/components/navbar";

const fredoka = Fredoka({ weight: ["400"], subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={fredoka.className}>
        <NavBar />
        {children}
      </body>
    </html>
  );
}
